# Generated by Django 4.2.11 on 2024-05-03 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('registration_plate', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Registration Plate')),
                ('brand', models.CharField(max_length=20, verbose_name='Brand')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('year', models.DateField(verbose_name='Year')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['registration_plate'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('rut', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='RUT')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver', to='fleetApp.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['rut'],
            },
        ),
        migrations.CreateModel(
            name='AccountingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('price', models.FloatField(verbose_name='Price')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contabilidad', to='fleetApp.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Accounting Record',
                'verbose_name_plural': 'Accounting Records',
                'ordering': ['purchase_date'],
            },
        ),
    ]
